config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "incomes#index"
  # get 'posts', to: "incomes#new"
	# post "incomes/index"
  resources :users, only: [:edit, :update]
  resources :incomes, only: [:new, :create, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  validates :total_income, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,  :validatable

  validates :name, presence: true, uniqueness: true
  has_many :incomes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/balance_confirm_controller.rb
class BalanceConfirmController < ApplicationController

  def top
  end

  def show
    @year_month = params[:year_month] + "-01"
		@incomes = Income.order(created_at: :asc)
		@fixedcosts = Fixedcost.order(created_at: :asc)
		@variablecosts = Variablecost.order(created_at: :asc)
 
		#収入計算
		@income_values =IncomeValue.where(year_month: @year_month)
		@income_value_total = 0	#収入合計
		@income_values.each do |income_value|
			@income_value_total += income_value.value
		end
 
		#固定費計算
		@fixedcost_values = FixedcostValue.where(year_month: @year_month)
		@fixedcost_value_total = 0 #固定費合計
		@fixedcost_values.each do |fixedcost_value|
			@fixedcost_value_total += fixedcost_value.value
		end
 
		#収支差
		@balance_difference = @income_value_total - (@fixedcost_value_total + @variablecost_value_total)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

	def index
		@income = Income.new
    # @incomes = Income.order(created_at: :asc)
	end
 
	def new
		@income = Income.new
	end
 
	def create
		@income = Income.new(income_params)
		if @income.save
			redirect_to income_path(@income.id), notice: "登録しました"
		else
			render :index
		end
	end
 
	def show
		@income = Income.find(params[:id])
		# 月利(年利15%)
		# 月単位の支払いなので、月利で計算します。loanrate
		interest_rate = @income.loanrate / 100 / 12
		# 支払い回数(5年)loanYear
		number_of_payments = @income.loanYear * 12
		# 借入金額
		borrowing_amount = @income.housing
	  @payment = Exonio.pmt(interest_rate, number_of_payments, borrowing_amount) * 12

		@graph = [
			{name: '収入', data: {"#{@income.myAge}歳" => @income.total_income, "#{@income.myAge + 5}歳" => @income.total_income, "#{@income.myAge + 10}歳" => @income.total_income, "#{@income.myAge + 15}歳" => @income.total_income, "#{@income.myAge + 20}歳" => @income.total_income, "#{@income.myAge + 25}歳" => @income.total_income, "#{@income.myAge + 30}歳" => @income.total_income, "#{@income.myAge + 35}歳" => @income.total_income, "#{@income.myAge + 40}歳" => @income.total_income, "#{@income.myAge + 45}歳" => @income.total_income}},
			{name: '出費', data: {"#{@income.myAge}歳" => @payment, "#{@income.myAge + 5}歳" => @payment, "#{@income.myAge + 10}歳" => @payment, "#{@income.myAge + 15}歳" => @payment, "#{@income.myAge + 20}歳" => @payment, "#{@income.myAge + 25}歳" => @payment, "#{@income.myAge + 30}歳" => @payment, "#{@income.myAge + 35}歳" => @payment, "#{@income.myAge + 40}歳" => @payment, "#{@income.myAge + 45}歳" => @payment}},
		];
		@balance = [{name: '貯蓄', data: {"#{@income.myAge}歳" => @income.total_income - @payment, "#{@income.myAge + 5}歳" => @income.total_income * 5 - @payment * 5, "#{@income.myAge + 10}歳" => @income.total_income * 10 - @payment * 10, "#{@income.myAge + 15}歳" => @income.total_income * 15 - @payment * 15, "#{@income.myAge + 20}歳" => @income.total_income * 20 - @payment * 20, "#{@income.myAge + 25}歳" => @income.total_income * 25 - @payment * 25, "#{@income.myAge + 30}歳" => @income.total_income * 30 - @payment * 30, "#{@income.myAge + 35}歳" => @income.total_income, "#{@income.myAge + 40}歳" => @income.total_income, "#{@income.myAge + 45}歳" => @income.total_income}},]
	end
 
	private
  def income_params
    params.require(:income).permit(:myAge, :total_income, :saving, :housing, :loanrate, :loanYear, :transportation, :event).merge(user_id: current_user.id)
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def edit
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_confirm_helper.rb
module BalanceConfirmHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/balance_confirm/show.html.erb
<h2><%= @year_month %> 収支確認</h2>
 

app/views/balance_confirm/top.html.erb
<h2>月次収支確認</h2>
 
<%= form_tag({controller: :balance_confirm, action: :show}, {method: :post}) do %>
	<input type="month" name="year_month">
	<input type="submit">
<% end %>

app/views/incomes/new.html.haml
.contents 支出について
.container 
  = form_with(model: @income, url: incomes_path(@income)) do |form|
    %P= form.label :living, "生活費"
    = form.text_field :name, placeholder: ""
    %p= form.label :living, "住宅関連費"
    = form.text_field :name, placeholder: ""
    %p= form.label :living, "交通費"
    = form.text_field :name, placeholder: ""
    %p= form.label :living, "教育費"
    = form.text_field :name, placeholder: ""
    %p= form.label :living, "保険料"
    = form.text_field :name, placeholder: ""
    %p= form.label :living, "その他"
    = form.text_field :name, placeholder: ""
    = form.submit "シュミレーションする", class: 'form-button'

app/views/incomes/show.html.haml
.wrapper
  %header
    .content.header-page
      %h1 シュミレーション結果
      .navbar
        .nav-user ユーザ名 :&nbsp
        = current_user.name
      .nav-link
      = link_to "Edit", destroy_user_session_path, method: :delete, class: 'Button'
  .advance
    .graph
      = line_chart @graph
  .advance
    .graph
      = line_chart @balance, colors: ["#66CC33", "#666"]

.btn-2
  = link_to "トップに戻る", root_path, class: "SubmitBtn"

-# = @payment
-# 年齢
-# = "#{@income.loanrate}"
-# 年収
-# = "#{@income.total_income}"
-# 貯蓄
-# = "#{@income.saving}"
-# housing
-# = "#{@income.housing}"
-# transportation
-# = "#{@income.transportation}"
-# event
-# = "#{@income.event}"

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lpsim
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/static_pages/top.html.haml
%h1 StaticPages#top
%p Find me in app/views/static_pages/top.html.erb

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", '#', class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'